### ISSUE TITLE
Integrate some aspects from https://github.com/DirkRusche/LaTeX ?

### ISSUE THREAD

**Issue by ifrh** [MartinX3-EducationOrganization/hbrs-latex-vorlage-arbeit#7]
Perhaps you can integrate some aspects of Dirk's old project?
https://github.com/DirkRusche/LaTeX

**Comment by ifrh** [comment]
Okay, du kammst schon auf die Idee des Kräfte bündelns: https://github.com/DirkRusche/LaTeX/issues/12

**Comment by MartinX3** [comment]
Ich schließ das mal hier.
Du kannst dich ja melden, wenn etwas offen ist.
